version: '3'
services:
  gateway:
    image: gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - cct-procject_default

  httpbin1:
    image: kennethreitz/httpbin
    ports:
      - 9080:80
    networks:
      - cct-procject_default

  httpbin2:
    image: kennethreitz/httpbin
    ports:
      - 7080:80
    networks:
      - cct-procject_default

  httpbin3:
    image: kennethreitz/httpbin
    ports:
      - 9180:80
    networks:
      - cct-procject_default

  httpbin4:
    image: kennethreitz/httpbin
    ports:
      - 7180:80
    networks:
      - cct-procject_default

networks:
  cct-procject_default:
