version: '3'
services:
  gateway:
    image: gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - api-network

  microservice:
    image: kennethreitz/httpbin
    ports:
      - 9080:80
    networks:
      - api-network

networks:
  api-network:
