version: '3'
services:
  gateway:
    image: gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - cct-procject_default

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 9080:80
    networks:
      - cct-procject_default

networks:
  cct-procject_default:
